### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Trogdayton** [ladylexxie/Perpetual-Durability#2]
I don't know whether I'm doing something wrong, or what? I used a nether star, tried it in the anvil, tried in the smithing table. Didn't do anything. Changed the config to a stick, tried both again, didn't work. Not entirely sure what I'm doing wrong. What info do you want from me to help diagnose the problem?

**Comment by lexxieblack** [comment]
What version are you playing on and what do your configs look like?

**Comment by Trogdayton** [comment]
I'm playing on 1.18.2 and I've also tried it on 1.19. I'll attach my config here, since apparently I can't drag and drop, I'll paste it.

[enchantments]

	[enchantments.perpetual]
		#ID of the item being used for getting the Perpetual Enchant [default: "minecraft:nether_star"]
		enchantItem = "minecraft:dirt"
		#List of the mods you want to blacklist
		#Example: 'perpetual'
		#default: []
		modBlacklist = []
		#List of the item IDs you want to blacklist
		#Example: 'minecraft:shield'
		#default: []
		itemBlacklist = []

The edit says dirt now, but I used minecraft:nether_star, and minecraft:stick as well. This is the 1.18.2. I actually already deleted the 1.19 pack and reinstalled, but I haven't run it yet again so I don't have the config. It looked the same I believe.

**Comment by lexxieblack** [comment]
And i forgot to ask what mod version are you on?

I'll test them now and see what's going on

**Comment by Trogdayton** [comment]
For the 1.18.2 mod it's version 1.3.0 which I believe is the latest.

**Comment by Trogdayton** [comment]
For the 1.19 it's currently the latest as well, which is 1.0.0 according to what I can find.

**Comment by lexxieblack** [comment]
What did you try to enchant? for me it works without any issues
![image](https://user-images.githubusercontent.com/30494658/177049140-720b709d-793b-455a-9257-98eab6590717.png)

**Comment by Trogdayton** [comment]
I believe it was a diamond pickaxe, but now I'm thinking it might have been a modded item, like from Gobber or something.
Can't honestly remember, sorry. Does it only work on vanilla tools?

**Comment by lexxieblack** [comment]
This should work on any item that has durability

**Comment by lexxieblack** [comment]
I just tried it with Gobber installed, and it works for me
I'm not sure what else to try


![image](https://user-images.githubusercontent.com/30494658/177050044-5a04ad54-885a-46a9-85a8-f9ae459e5505.png)
![image](https://user-images.githubusercontent.com/30494658/177050048-0e1b087f-7c8a-4698-8e33-3dbb3af54786.png)

**Comment by Trogdayton** [comment]
Fair enough, I'll leave this as closed for now, presumably I just did something wrong. I tend to mod my games to the breaking point, so it's likely my fault. Thanks for your time!
