### ISSUE TITLE
[Request]: Fabric port?

### ISSUE THREAD

**Issue by Trogdayton** [ladylexxie/Perpetual-Durability#3]
Simple question. Is this portable to Fabric, and if so would you? I understand if you say no, it's asking you to do extra work. Just curious. I freaking love this mod.

**Comment by Trogdayton** [comment]
I... don't seem to be able to add a label? I was going to label it as enhancement, since there's not a request label.

**Comment by lexxieblack** [comment]
Thanks for using my mod <3

The problem is I have zero experience with Fabric, so it would be quite difficult, but I suppose it is something I can look into.

**Comment by Trogdayton** [comment]
That's fair, I don't either from a modding perspective. Thanks for the
reply!
