### ISSUE TITLE
[Bug]: 1.19.2 - No longer works - Tools Etc Breaks When Used By Fake Players Such As Machines Minecolonist Etc.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ladylexxie/Perpetual-Durability#4]
### Minecraft Version

1.19

### Mod Verion

perpetual_durability-1.19.2-2.0.0

### What happened?

They break especially when used with refined storage this mod is no longer perpetual. What exactly did the re-write which I never had problems with before do?

**Comment by P3rf3ctXZer0** [comment]
#Some helpful information
Has the proper tag looses durability when used by fake players minecolonist machines anything not directly wielded by the player.

#Test Environment
Dedicated Server https://www.curseforge.com/minecraft/modpacks/fiction-friction-pixelmon/files/4432495

**Comment by P3rf3ctXZer0** [comment]
nevermind still has that problem with refined storage ... but I know it was not an issue with Mine colonies.

**Comment by lexxieblack** [comment]
The rewrite was to change from enchant to the built-in tag added by Minecraft.
Every time an item takes durability, it will check if the item has that tag, and if it does, it will just not do damage to it.

I will investigate this more with fakeplayers and see if I can figure out why it's happening, because it really shouldn't.

**Comment by lexxieblack** [comment]
In our testing, it seemed like Minecolonies works with no issues with the tag. Can you show me a screenshot of the tool you've given them?
Also, I'm not sure what you mean by a problem with Refined Storage. What block uses tools?

**Comment by P3rf3ctXZer0** [comment]
I gave the a pickletweaks wood paxel - mind you my world is 940 in game days old. As far as refined storage goes I was using the copper hammer to make dust and it straight vanished. It could be because of bigger stacks being 2k per stack and I had past the 256 in durability for the operation.

**Comment by lexxieblack** [comment]
Were these tools updated from the enchant to tag? They will automatically update instantly when a player gets them in their inventory, which is why i wanted to see the screenshot of the tool.

**Comment by P3rf3ctXZer0** [comment]
... Sorry at any rate it seems to be fixed. Whatever you changed. I will re-open if I find it to still be an issue. I will take screenshots etc then as well.
