### ISSUE TITLE
[Question]: How do I use the new tag system - this all that I see and I don't see where to set the item.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ladylexxie/Perpetual-Durability#5]
### What would you like to know?

This is what a fresh config for 1.19.4 looks like.

``
[blacklist]
	#List of the mods you want to blacklist
	#Example: ["perpetual", "botania"]
	#default: []
	mods = []
	#List of the item IDs you want to blacklist
	#Example: ["minecraft:shield", "minecraft:diamond_sword"]
	#default: []
	items = []
	#List of the item tags you want to blacklist
	#Example: ["forge:tools/shovel"]
	#default: []
	tags = []

``

``Configuring The Mod

This mod creates a config file called `perpetual_durability-common.toml` in the /config/ folder
The config file has 3 fields:
    1. enchantItem: the ID of the item you want to use for applying the effect

    2. modBlacklist: a list of blacklisted mods. None of the mod items will be able to get the effect

    3. itemBlacklist: a list of blacklisted items. None of the items will be able to get the effect``
    
This is what your front page says so I am really confused.

![7CWMXRi 1](https://user-images.githubusercontent.com/10351221/225507930-d47f654e-7ecc-4f7c-bffb-70541d7e4b00.png)

**Comment by lexxieblack** [comment]
The 1.19.4 version is only a beta version, it's not finished and it's still work in progress.
I've been working on a lot of changes in my `1.19.3-dev` branch, and most of them were ported over.

For now, to get it working, you need to add the [`perpetual_durability:perpetual`](https://github.com/ladylexxie/Perpetual-Durability/blob/1.19.4/src/main/java/ladylexxie/perpetual_durability/registry/PRegistry.java#L19) tag to any item. I forgot to upload the default one from the other branch, I will do it when I'm home from work.

[This](https://github.com/ladylexxie/Perpetual-Durability/blob/1.19.3-dev/src/main/resources/data/perpetual_durability/tags/items/perpetual.json) is what the default value will be when I fix it. you can manually add this file for now, and add any item IDs you want in that list. Those items will act as the catalyst to make items unbreakable.

**Comment by lexxieblack** [comment]
A lot of changes will come soon, and when they are properly released, I will update the descriptions as well, and possibly add a small Wiki page for more detailed information.
