### ISSUE TITLE
[Bug]: Recipe Errors on Dedicated Server

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ladylexxie/Perpetual-Durability#6]
### Minecraft Version

1.19.4

### Mod Verion

perpetual_durability-1.19.4-0.3.0.jar

### What happened?

Though nothing is crashing this seems like relevant information.

https://gist.github.com/P3rf3ctXZer0/132146f78612a7b4c4df2e071123a9e7

### Crash Log

NA

**Comment by lexxieblack** [comment]
Ah I forgot to rename something while reworking the mod...
Thanks for reminding me, will fix it asap :D
