### ISSUE TITLE
[Bug]: Command doesn't seem to be present or work in v1.19.4

### ISSUE THREAD

**Issue by nomad-software** [ladylexxie/Perpetual-Durability#8]
### Minecraft Version

1.19.4

### Mod Verion

perpetual_durability-1.19.4-0.3.2.jar

### What happened?

Nothing seems to happen when I use the `/perpetuate` command as [described in the wiki](https://github.com/ladylexxie/Perpetual-Durability/wiki/Using-The-Command). In fact, I get an error saying command not recognised.

I'm using version ForgeOptiFine v1.19.4 through Tlauncher v2.879.

**Comment by nomad-software** [comment]
I needed to create the world in cheat mode. 🤦

**Comment by lexxieblack** [comment]
It is the equivalent of the vanilla `/enchant` command, they are both OP only :D

Sorry for not replying earlier, very busy IRL :/
